# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_and_test:
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "grideyelib/build.gradle" }}
        - v1-dependencies-
    - run:
        name: gradle dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: -v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "grideyelib/build.gradle" }}
    # run tests!
    - run:
        name: gradle test
        command: |
          ./gradlew test
          ./gradlew test lint

    - store_test_results:
        path: grideyelib/build/test-results

    - store_artifacts:
        path: grideyelib/build/test-results

  release:
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - checkout
    -restore_cache:
      keys:
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "grideyelib/build.gradle" }}
    - v1-dependencies-
    - run:
        name: gradle dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: -v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "grideyelib/build.gradle" }}
    # run tests!
    - run:
        name: gradle test
        command: |
          ./gradlew test
          ./gradlew test lint

    - store_test_results:
        path: grideyelib/build/test-results

    - store_artifacts:
        path: grideyelib/build/test-results

    - run:
        name: gradle uplaod
        command: ./gradlew bintrayUpload



workflows:
  version: 1
  jobs:
  - build_and_test:
      filters:
        branches:
          only: /.*/
        tags:
          only: /.*/
  - release:
      filters:
        branches:
          ignore: /.*/
        tags:
          only: /^v[0-9](\.[0-9]){2}$/


